### ISSUE TITLE
isSorted

### ISSUE THREAD

**Issue by elizabethsiegle** [elizabethsiegle/30-seconds-of-swift-code#11]
Make a function that returns 1 if the array is sorted in ascending order, -1 if it is sorted in descending order, or 0 if the array is not sorted.

**Comment by HelioStrike** [comment]
I'd like to work on this

**Comment by elizabethsiegle** [comment]
Sounds good, @HelioStrike!

**Comment by NatashaChhibber707** [comment]
I'd like work on this , Please assign it to me

**Comment by elizabethsiegle** [comment]
It's already been completed and merged! @NatashaChhibber707
