### ISSUE TITLE
Flatten

### ISSUE THREAD

**Issue by elizabethsiegle** [elizabethsiegle/30-seconds-of-swift-code#4]
Make a function that flattens a list of lists once.

**Comment by VedantParanjape** [comment]
what do you mean by flattens? could you be more specific

**Comment by elizabethsiegle** [comment]
@VedantParanjape like this: https://github.com/30-seconds/30-seconds-of-python#flatten

**Comment by VedantParanjape** [comment]
cool

**Comment by EgorKolyshkin** [comment]
What this function should do with optionals?
