### ISSUE TITLE
every_nth

### ISSUE THREAD

**Issue by elizabethsiegle** [elizabethsiegle/30-seconds-of-swift-code#5]
Make a function that returns every nth element in a list: use `[nth-1::nth]` to create a new list that contains every nth element of the given list.

**Comment by phjs** [comment]
I work on that

**Comment by Will-1-Am** [comment]
Is this repo meant to be forked first, or are the PRs meant to be iniated from the main repo?

**Comment by elizabethsiegle** [comment]
fork, please! @Will-1-Am!

**Comment by NatashaChhibber707** [comment]
I would like to work on it

**Comment by elizabethsiegle** [comment]
It's already been completed and merged! @NatashaChhibber707
