### ISSUE TITLE
camel case to snake case

### ISSUE THREAD

**Issue by elizabethsiegle** [elizabethsiegle/30-seconds-of-swift-code#7]
Convert camel case (initial capital is used for the first letter of a word forming the second element of a closed compound, like 'PayPal' or 'iPhone') to snake case (separate words/elements with one underscore character and no spaces, like 'this_is_snake_case'). Overall, like [this](https://gist.github.com/dmsl1805/ad9a14b127d0409cf9621dc13d237457).

**Comment by criticic** [comment]
i want to work on this

**Comment by elizabethsiegle** [comment]
I'd love it if you did @fluctix! This is [one way to do it in Python](https://stackoverflow.com/questions/1175208/elegant-python-function-to-convert-camelcase-to-snake-case) and [here in JavaScript.](https://stackoverflow.com/questions/54246477/how-to-convert-camelcase-to-snake-case). This is in [Swift](https://gist.github.com/ivanbruel/e72d938f49db64d2f5df09fb9420c1e2).

**Comment by aekosyakov** [comment]
Hi, @fluctix , @elizabethsiegle!  What is a progress of the issue? May I upload a PR with solution? Tnx!

**Comment by elizabethsiegle** [comment]
I will merge the first PR I see that works!

**Comment by aekosyakov** [comment]
Hi, great news, thanx!
